
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jan  7 2026 09:16:18 IST (Jan  7 2026 03:46:18 UTC)

// Verification Directory fv/round_robin_interconnect 

module round_robin_interconnect(clk, rst_n, req_i, addr_i, wdata_i,
     we_i, gnt_o, slave_valid_o, slave_addr_o, slave_wdata_o,
     slave_we_o, slave_ready_i, slave_rdata_i);
  input clk, rst_n, slave_ready_i;
  input [3:0] req_i, we_i;
  input [127:0] addr_i, wdata_i;
  input [31:0] slave_rdata_i;
  output [3:0] gnt_o;
  output slave_valid_o, slave_we_o;
  output [31:0] slave_addr_o, slave_wdata_o;
  wire clk, rst_n, slave_ready_i;
  wire [3:0] req_i, we_i;
  wire [127:0] addr_i, wdata_i;
  wire [31:0] slave_rdata_i;
  wire [3:0] gnt_o;
  wire slave_valid_o, slave_we_o;
  wire [31:0] slave_addr_o, slave_wdata_o;
  wire [3:0] pointer_reg;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_186, n_187, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228;
  SDFFRHQX1 \gnt_o_reg[0] (.RN (rst_n), .CK (clk), .D (n_228), .SI
       (gnt_o[0]), .SE (n_226), .Q (gnt_o[0]));
  SDFFRHQX1 \pointer_reg_reg[1] (.RN (rst_n), .CK (clk), .D
       (pointer_reg[1]), .SI (n_228), .SE (n_227), .Q (pointer_reg[1]));
  DFFRX2 \gnt_o_reg[3] (.RN (rst_n), .CK (clk), .D (n_224), .Q
       (gnt_o[3]), .QN (UNCONNECTED));
  SDFFSHQX1 \pointer_reg_reg[0] (.SN (rst_n), .CK (clk), .D
       (pointer_reg[0]), .SI (n_222), .SE (n_227), .Q (pointer_reg[0]));
  SDFFRHQX1 \gnt_o_reg[1] (.RN (rst_n), .CK (clk), .D (n_225), .SI
       (gnt_o[1]), .SE (n_226), .Q (gnt_o[1]));
  SDFFRHQX1 \pointer_reg_reg[2] (.RN (rst_n), .CK (clk), .D
       (pointer_reg[2]), .SI (n_225), .SE (n_227), .Q (pointer_reg[2]));
  SDFFRHQX1 \pointer_reg_reg[3] (.RN (rst_n), .CK (clk), .D
       (pointer_reg[3]), .SI (n_223), .SE (n_227), .Q (pointer_reg[3]));
  OAI22X1 g5573__2398(.A0 (n_221), .A1 (n_226), .B0 (n_150), .B1 (n_1),
       .Y (n_224));
  SDFFRHQX1 \gnt_o_reg[2] (.RN (rst_n), .CK (clk), .D (n_223), .SI
       (gnt_o[2]), .SE (n_226), .Q (gnt_o[2]));
  NOR2BXL g5575__5107(.AN (req_i[0]), .B (n_220), .Y (n_228));
  INVXL g5577(.A (n_221), .Y (n_222));
  AOI32X1 g5579__6260(.A0 (n_187), .A1 (n_186), .A2 (req_i[3]), .B0
       (n_121), .B1 (n_2), .Y (n_221));
  AOI22X1 g5578__4319(.A0 (n_107), .A1 (n_8), .B0 (n_7), .B1 (n_151),
       .Y (n_220));
  AND2X2 g5576__8428(.A (n_152), .B (req_i[1]), .Y (n_225));
  NAND2XL g5633__5526(.A (n_82), .B (n_85), .Y (slave_addr_o[12]));
  NAND2XL g5595__6783(.A (n_110), .B (n_149), .Y (slave_addr_o[5]));
  NAND2XL g5627__3680(.A (n_109), .B (n_113), .Y (slave_wdata_o[28]));
  NAND2XL g5641__1617(.A (n_56), .B (n_60), .Y (slave_wdata_o[20]));
  NAND2XL g5607__2802(.A (n_29), .B (n_51), .Y (slave_wdata_o[4]));
  NAND2XL g5618__1705(.A (n_64), .B (n_141), .Y (slave_addr_o[31]));
  NAND2XL g5622__5122(.A (n_17), .B (n_70), .Y (slave_addr_o[30]));
  NAND2XL g5596__8246(.A (n_25), .B (n_72), .Y (slave_addr_o[29]));
  NAND2XL g5599__7098(.A (n_43), .B (n_100), .Y (slave_addr_o[4]));
  NAND2XL g5619__6131(.A (n_23), .B (n_119), .Y (slave_addr_o[28]));
  NAND2XL g5623__1881(.A (n_20), .B (n_61), .Y (slave_addr_o[27]));
  NAND2XL g5581__5115(.A (n_13), .B (n_103), .Y (slave_addr_o[26]));
  NAND2XL g5584__7482(.A (n_59), .B (n_74), .Y (slave_addr_o[8]));
  NAND2XL g5592__4733(.A (n_32), .B (n_48), .Y (slave_addr_o[25]));
  NAND2XL g5612__6161(.A (n_24), .B (n_124), .Y (slave_addr_o[24]));
  NAND2XL g5625__9315(.A (n_89), .B (n_108), .Y (slave_addr_o[23]));
  NAND2XL g5600__9945(.A (n_33), .B (n_96), .Y (slave_wdata_o[8]));
  NAND2XL g5629__2883(.A (n_21), .B (n_77), .Y (slave_addr_o[22]));
  NAND2XL g5635__2346(.A (n_22), .B (n_87), .Y (slave_addr_o[21]));
  NAND2XL g5582__1666(.A (n_15), .B (n_52), .Y (slave_addr_o[20]));
  NAND2XL g5593__7410(.A (n_36), .B (n_123), .Y (slave_addr_o[19]));
  NAND2XL g5598__6417(.A (n_62), .B (n_90), .Y (slave_addr_o[18]));
  NAND2XL g5603__5477(.A (n_40), .B (n_58), .Y (slave_addr_o[17]));
  NAND2XL g5616__2398(.A (n_131), .B (n_137), .Y (slave_addr_o[16]));
  NAND2XL g5620__5107(.A (n_115), .B (n_127), .Y (slave_addr_o[15]));
  NAND2XL g5626__6260(.A (n_104), .B (n_111), .Y (slave_addr_o[14]));
  NAND2XL g5630__4319(.A (n_138), .B (n_99), .Y (slave_addr_o[13]));
  NAND2XL g5636__8428(.A (n_68), .B (n_75), .Y (slave_addr_o[11]));
  NAND2XL g5640__5526(.A (n_50), .B (n_57), .Y (slave_addr_o[10]));
  NAND2XL g5642__6783(.A (n_112), .B (n_49), .Y (slave_addr_o[9]));
  NAND2XL g5587__3680(.A (n_140), .B (n_42), .Y (slave_addr_o[7]));
  NAND2XL g5589__1617(.A (n_129), .B (n_133), .Y (slave_addr_o[6]));
  AOI31X1 g5699__2802(.A0 (n_187), .A1 (n_186), .A2 (n_0), .B0 (n_226),
       .Y (n_227));
  NAND2XL g5644__1705(.A (n_98), .B (n_47), .Y (slave_wdata_o[18]));
  NAND2XL g5606__5122(.A (n_44), .B (n_55), .Y (slave_addr_o[2]));
  NAND2XL g5608__8246(.A (n_146), .B (n_41), .Y (slave_addr_o[1]));
  NAND2XL g5613__7098(.A (n_136), .B (n_116), .Y (slave_addr_o[0]));
  NAND2XL g5617__6131(.A (n_128), .B (n_132), .Y (slave_wdata_o[31]));
  NAND2XL g5621__1881(.A (n_122), .B (n_125), .Y (slave_wdata_o[30]));
  NAND2XL g5624__5115(.A (n_117), .B (n_118), .Y (slave_wdata_o[29]));
  NAND2XL g5628__7482(.A (n_101), .B (n_102), .Y (slave_wdata_o[27]));
  NAND2XL g5631__4733(.A (n_95), .B (n_97), .Y (slave_wdata_o[26]));
  NAND2XL g5632__6161(.A (n_65), .B (n_93), .Y (slave_wdata_o[25]));
  NAND2XL g5637__9315(.A (n_78), .B (n_81), .Y (slave_wdata_o[23]));
  NAND2XL g5638__9945(.A (n_71), .B (n_73), .Y (slave_wdata_o[22]));
  NAND2XL g5639__2883(.A (n_63), .B (n_67), .Y (slave_wdata_o[21]));
  NAND2XL g5634__2346(.A (n_84), .B (n_88), .Y (slave_wdata_o[24]));
  NAND2XL g5591__1666(.A (n_37), .B (n_135), .Y (slave_wdata_o[12]));
  NAND2XL g5643__7410(.A (n_53), .B (n_54), .Y (slave_wdata_o[19]));
  NAND2XL g5604__6417(.A (n_69), .B (n_79), .Y (slave_addr_o[3]));
  NAND2XL g5583__5477(.A (n_16), .B (n_94), .Y (slave_wdata_o[17]));
  NAND2XL g5585__2398(.A (n_66), .B (n_80), .Y (slave_wdata_o[16]));
  NAND2XL g5586__5107(.A (n_14), .B (n_46), .Y (slave_wdata_o[15]));
  NAND2XL g5588__6260(.A (n_120), .B (n_39), .Y (slave_wdata_o[14]));
  NAND2XL g5590__4319(.A (n_38), .B (n_142), .Y (slave_wdata_o[13]));
  NAND2XL g5594__8428(.A (n_35), .B (n_126), .Y (slave_wdata_o[11]));
  NAND2XL g5580__5526(.A (n_19), .B (n_114), .Y (slave_wdata_o[10]));
  NAND2XL g5597__6783(.A (n_34), .B (n_130), .Y (slave_wdata_o[9]));
  NAND2XL g5601__3680(.A (n_83), .B (n_86), .Y (slave_wdata_o[7]));
  NAND2XL g5602__1617(.A (n_31), .B (n_76), .Y (slave_wdata_o[6]));
  NAND2XL g5605__2802(.A (n_30), .B (n_91), .Y (slave_wdata_o[5]));
  NAND2XL g5609__1705(.A (n_28), .B (n_45), .Y (slave_wdata_o[3]));
  NAND2XL g5610__5122(.A (n_27), .B (n_148), .Y (slave_wdata_o[2]));
  NAND2XL g5611__8246(.A (n_18), .B (n_143), .Y (slave_wdata_o[1]));
  NAND2XL g5614__7098(.A (n_26), .B (n_144), .Y (slave_wdata_o[0]));
  NAND2XL g5615__6131(.A (n_12), .B (n_134), .Y (slave_we_o));
  OAI22XL g5645__1881(.A0 (n_9), .A1 (req_i[0]), .B0 (n_151), .B1
       (pointer_reg[1]), .Y (n_152));
  INVXL g5753(.A (n_226), .Y (n_150));
  OAI21XL g5646__5115(.A0 (n_11), .A1 (n_106), .B0 (n_6), .Y (n_223));
  AOI22XL g5670__7482(.A0 (n_147), .A1 (addr_i[37]), .B0 (gnt_o[3]),
       .B1 (addr_i[101]), .Y (n_149));
  AOI22X1 g5695__4733(.A0 (n_145), .A1 (wdata_i[2]), .B0 (n_147), .B1
       (wdata_i[34]), .Y (n_148));
  AOI22XL g5696__6161(.A0 (n_145), .A1 (addr_i[1]), .B0 (n_139), .B1
       (addr_i[65]), .Y (n_146));
  AOI22X1 g5726__9315(.A0 (n_145), .A1 (wdata_i[0]), .B0 (n_147), .B1
       (wdata_i[32]), .Y (n_144));
  AOI22X1 g5697__9945(.A0 (n_145), .A1 (wdata_i[1]), .B0 (n_147), .B1
       (wdata_i[33]), .Y (n_143));
  AOI22X1 g5663__2883(.A0 (n_145), .A1 (wdata_i[13]), .B0 (n_147), .B1
       (wdata_i[45]), .Y (n_142));
  AOI22XL g5698__2346(.A0 (n_147), .A1 (addr_i[63]), .B0 (gnt_o[3]),
       .B1 (addr_i[127]), .Y (n_141));
  AOI22XL g5664__1666(.A0 (n_145), .A1 (addr_i[7]), .B0 (n_139), .B1
       (addr_i[71]), .Y (n_140));
  AOI22XL g5700__7410(.A0 (n_145), .A1 (addr_i[13]), .B0 (n_139), .B1
       (addr_i[77]), .Y (n_138));
  AOI22XL g5701__6417(.A0 (n_147), .A1 (addr_i[48]), .B0 (gnt_o[3]),
       .B1 (addr_i[112]), .Y (n_137));
  AOI22XL g5702__5477(.A0 (n_145), .A1 (addr_i[0]), .B0 (n_139), .B1
       (addr_i[64]), .Y (n_136));
  AOI22X1 g5665__2398(.A0 (n_145), .A1 (wdata_i[12]), .B0 (n_147), .B1
       (wdata_i[44]), .Y (n_135));
  AOI22X1 g5703__5107(.A0 (n_145), .A1 (we_i[0]), .B0 (n_147), .B1
       (we_i[1]), .Y (n_134));
  AOI22XL g5666__6260(.A0 (n_147), .A1 (addr_i[38]), .B0 (gnt_o[3]),
       .B1 (addr_i[102]), .Y (n_133));
  AOI22XL g5704__4319(.A0 (n_147), .A1 (wdata_i[63]), .B0 (gnt_o[3]),
       .B1 (wdata_i[127]), .Y (n_132));
  AOI22XL g5705__8428(.A0 (n_145), .A1 (addr_i[16]), .B0 (n_139), .B1
       (addr_i[80]), .Y (n_131));
  AOI22X1 g5647__5526(.A0 (n_145), .A1 (wdata_i[9]), .B0 (n_147), .B1
       (wdata_i[41]), .Y (n_130));
  AOI22XL g5667__6783(.A0 (n_145), .A1 (addr_i[6]), .B0 (n_139), .B1
       (addr_i[70]), .Y (n_129));
  AOI22XL g5706__3680(.A0 (n_145), .A1 (wdata_i[31]), .B0 (n_139), .B1
       (wdata_i[95]), .Y (n_128));
  AOI22XL g5707__1617(.A0 (n_147), .A1 (addr_i[47]), .B0 (gnt_o[3]),
       .B1 (addr_i[111]), .Y (n_127));
  AOI22X1 g5668__2802(.A0 (n_145), .A1 (wdata_i[11]), .B0 (n_147), .B1
       (wdata_i[43]), .Y (n_126));
  AOI22XL g5708__1705(.A0 (n_147), .A1 (wdata_i[62]), .B0 (gnt_o[3]),
       .B1 (wdata_i[126]), .Y (n_125));
  AOI22X1 g5709__5122(.A0 (n_145), .A1 (addr_i[24]), .B0 (n_147), .B1
       (addr_i[56]), .Y (n_124));
  AOI22X1 g5669__8246(.A0 (n_145), .A1 (addr_i[19]), .B0 (n_147), .B1
       (addr_i[51]), .Y (n_123));
  AOI22XL g5710__7098(.A0 (n_145), .A1 (wdata_i[30]), .B0 (n_139), .B1
       (wdata_i[94]), .Y (n_122));
  OAI21XL g5648__6131(.A0 (n_4), .A1 (req_i[1]), .B0 (n_105), .Y
       (n_121));
  AOI22XL g5662__1881(.A0 (n_145), .A1 (wdata_i[14]), .B0 (n_139), .B1
       (wdata_i[78]), .Y (n_120));
  AOI22X1 g5711__5115(.A0 (n_145), .A1 (addr_i[28]), .B0 (n_147), .B1
       (addr_i[60]), .Y (n_119));
  AOI22XL g5712__7482(.A0 (n_147), .A1 (wdata_i[61]), .B0 (gnt_o[3]),
       .B1 (wdata_i[125]), .Y (n_118));
  AOI22XL g5713__4733(.A0 (n_145), .A1 (wdata_i[29]), .B0 (n_139), .B1
       (wdata_i[93]), .Y (n_117));
  AOI22XL g5649__6161(.A0 (n_147), .A1 (addr_i[32]), .B0 (gnt_o[3]),
       .B1 (addr_i[96]), .Y (n_116));
  AOI22XL g5714__9315(.A0 (n_145), .A1 (addr_i[15]), .B0 (n_139), .B1
       (addr_i[79]), .Y (n_115));
  AOI22X1 g5671__9945(.A0 (n_145), .A1 (wdata_i[10]), .B0 (n_147), .B1
       (wdata_i[42]), .Y (n_114));
  AOI22XL g5715__2883(.A0 (n_147), .A1 (wdata_i[60]), .B0 (gnt_o[3]),
       .B1 (wdata_i[124]), .Y (n_113));
  AOI22XL g5650__2346(.A0 (n_145), .A1 (addr_i[9]), .B0 (n_139), .B1
       (addr_i[73]), .Y (n_112));
  AOI22XL g5716__1666(.A0 (n_147), .A1 (addr_i[46]), .B0 (gnt_o[3]),
       .B1 (addr_i[110]), .Y (n_111));
  AOI22XL g5672__7410(.A0 (n_145), .A1 (addr_i[5]), .B0 (n_139), .B1
       (addr_i[69]), .Y (n_110));
  AOI22XL g5717__6417(.A0 (n_145), .A1 (wdata_i[28]), .B0 (n_139), .B1
       (wdata_i[92]), .Y (n_109));
  AOI22XL g5718__5477(.A0 (n_147), .A1 (addr_i[55]), .B0 (gnt_o[3]),
       .B1 (addr_i[119]), .Y (n_108));
  OAI2BB1X1 g5673__2398(.A0N (n_10), .A1N (n_106), .B0 (n_105), .Y
       (n_107));
  AOI22XL g5719__5107(.A0 (n_145), .A1 (addr_i[14]), .B0 (n_139), .B1
       (addr_i[78]), .Y (n_104));
  AOI22X1 g5674__6260(.A0 (n_145), .A1 (addr_i[26]), .B0 (n_147), .B1
       (addr_i[58]), .Y (n_103));
  AOI22XL g5720__4319(.A0 (n_147), .A1 (wdata_i[59]), .B0 (gnt_o[3]),
       .B1 (wdata_i[123]), .Y (n_102));
  AOI22XL g5721__8428(.A0 (n_145), .A1 (wdata_i[27]), .B0 (n_139), .B1
       (wdata_i[91]), .Y (n_101));
  AOI22XL g5675__5526(.A0 (n_147), .A1 (addr_i[36]), .B0 (gnt_o[3]),
       .B1 (addr_i[100]), .Y (n_100));
  AOI22XL g5722__6783(.A0 (n_147), .A1 (addr_i[45]), .B0 (gnt_o[3]),
       .B1 (addr_i[109]), .Y (n_99));
  AOI22XL g5651__3680(.A0 (n_145), .A1 (wdata_i[18]), .B0 (n_139), .B1
       (wdata_i[82]), .Y (n_98));
  AOI22XL g5723__1617(.A0 (n_147), .A1 (wdata_i[58]), .B0 (gnt_o[3]),
       .B1 (wdata_i[122]), .Y (n_97));
  AOI22X1 g5676__2802(.A0 (n_145), .A1 (wdata_i[8]), .B0 (n_147), .B1
       (wdata_i[40]), .Y (n_96));
  AOI22XL g5724__1705(.A0 (n_145), .A1 (wdata_i[26]), .B0 (n_139), .B1
       (wdata_i[90]), .Y (n_95));
  AOI22X1 g5652__5122(.A0 (n_145), .A1 (wdata_i[17]), .B0 (n_147), .B1
       (wdata_i[49]), .Y (n_94));
  AOI22XL g5725__8246(.A0 (n_147), .A1 (wdata_i[57]), .B0 (gnt_o[3]),
       .B1 (wdata_i[121]), .Y (n_93));
  NOR2BX1 g5769__7098(.AN (slave_valid_o), .B (slave_ready_i), .Y
       (n_226));
  AOI22X1 g5685__6131(.A0 (n_145), .A1 (wdata_i[5]), .B0 (n_147), .B1
       (wdata_i[37]), .Y (n_91));
  AOI22XL g5677__1881(.A0 (n_147), .A1 (addr_i[50]), .B0 (gnt_o[3]),
       .B1 (addr_i[114]), .Y (n_90));
  AOI22XL g5728__5115(.A0 (n_145), .A1 (addr_i[23]), .B0 (n_139), .B1
       (addr_i[87]), .Y (n_89));
  AOI22XL g5729__7482(.A0 (n_147), .A1 (wdata_i[56]), .B0 (gnt_o[3]),
       .B1 (wdata_i[120]), .Y (n_88));
  AOI22X1 g5653__4733(.A0 (n_145), .A1 (addr_i[21]), .B0 (n_147), .B1
       (addr_i[53]), .Y (n_87));
  AOI22XL g5679__6161(.A0 (n_147), .A1 (wdata_i[39]), .B0 (gnt_o[3]),
       .B1 (wdata_i[103]), .Y (n_86));
  AOI22XL g5730__9315(.A0 (n_147), .A1 (addr_i[44]), .B0 (gnt_o[3]),
       .B1 (addr_i[108]), .Y (n_85));
  AOI22XL g5731__9945(.A0 (n_145), .A1 (wdata_i[24]), .B0 (n_139), .B1
       (wdata_i[88]), .Y (n_84));
  AOI22XL g5680__2883(.A0 (n_145), .A1 (wdata_i[7]), .B0 (n_139), .B1
       (wdata_i[71]), .Y (n_83));
  AOI22XL g5732__2346(.A0 (n_145), .A1 (addr_i[12]), .B0 (n_139), .B1
       (addr_i[76]), .Y (n_82));
  AOI22XL g5733__1666(.A0 (n_147), .A1 (wdata_i[55]), .B0 (gnt_o[3]),
       .B1 (wdata_i[119]), .Y (n_81));
  AOI22XL g5654__7410(.A0 (n_147), .A1 (wdata_i[48]), .B0 (gnt_o[3]),
       .B1 (wdata_i[112]), .Y (n_80));
  AOI22XL g5681__6417(.A0 (n_147), .A1 (addr_i[35]), .B0 (gnt_o[3]),
       .B1 (addr_i[99]), .Y (n_79));
  AOI22XL g5734__5477(.A0 (n_145), .A1 (wdata_i[23]), .B0 (n_139), .B1
       (wdata_i[87]), .Y (n_78));
  AOI22X1 g5735__2398(.A0 (n_145), .A1 (addr_i[22]), .B0 (n_147), .B1
       (addr_i[54]), .Y (n_77));
  AOI22X1 g5682__5107(.A0 (n_145), .A1 (wdata_i[6]), .B0 (n_147), .B1
       (wdata_i[38]), .Y (n_76));
  AOI22XL g5736__6260(.A0 (n_147), .A1 (addr_i[43]), .B0 (gnt_o[3]),
       .B1 (addr_i[107]), .Y (n_75));
  AOI22XL g5655__4319(.A0 (n_147), .A1 (addr_i[40]), .B0 (gnt_o[3]),
       .B1 (addr_i[104]), .Y (n_74));
  AOI22XL g5737__8428(.A0 (n_147), .A1 (wdata_i[54]), .B0 (gnt_o[3]),
       .B1 (wdata_i[118]), .Y (n_73));
  AOI22X1 g5683__5526(.A0 (n_145), .A1 (addr_i[29]), .B0 (n_147), .B1
       (addr_i[61]), .Y (n_72));
  AOI22XL g5738__6783(.A0 (n_145), .A1 (wdata_i[22]), .B0 (n_139), .B1
       (wdata_i[86]), .Y (n_71));
  AOI22X1 g5739__3680(.A0 (n_145), .A1 (addr_i[30]), .B0 (n_147), .B1
       (addr_i[62]), .Y (n_70));
  AOI22XL g5684__1617(.A0 (n_145), .A1 (addr_i[3]), .B0 (n_139), .B1
       (addr_i[67]), .Y (n_69));
  AOI22XL g5740__2802(.A0 (n_145), .A1 (addr_i[11]), .B0 (n_139), .B1
       (addr_i[75]), .Y (n_68));
  AOI22XL g5741__1705(.A0 (n_147), .A1 (wdata_i[53]), .B0 (gnt_o[3]),
       .B1 (wdata_i[117]), .Y (n_67));
  AOI22XL g5656__5122(.A0 (n_145), .A1 (wdata_i[16]), .B0 (n_139), .B1
       (wdata_i[80]), .Y (n_66));
  AOI22XL g5727__8246(.A0 (n_145), .A1 (wdata_i[25]), .B0 (n_139), .B1
       (wdata_i[89]), .Y (n_65));
  AOI22XL g5742__7098(.A0 (n_145), .A1 (addr_i[31]), .B0 (n_139), .B1
       (addr_i[95]), .Y (n_64));
  AOI22XL g5743__6131(.A0 (n_145), .A1 (wdata_i[21]), .B0 (n_139), .B1
       (wdata_i[85]), .Y (n_63));
  AOI22XL g5686__1881(.A0 (n_145), .A1 (addr_i[18]), .B0 (n_139), .B1
       (addr_i[82]), .Y (n_62));
  AOI22X1 g5744__5115(.A0 (n_145), .A1 (addr_i[27]), .B0 (n_147), .B1
       (addr_i[59]), .Y (n_61));
  AOI22XL g5745__7482(.A0 (n_147), .A1 (wdata_i[52]), .B0 (gnt_o[3]),
       .B1 (wdata_i[116]), .Y (n_60));
  AOI22XL g5657__4733(.A0 (n_145), .A1 (addr_i[8]), .B0 (n_139), .B1
       (addr_i[72]), .Y (n_59));
  AOI22XL g5687__6161(.A0 (n_147), .A1 (addr_i[49]), .B0 (gnt_o[3]),
       .B1 (addr_i[113]), .Y (n_58));
  AOI22XL g5746__9315(.A0 (n_147), .A1 (addr_i[42]), .B0 (gnt_o[3]),
       .B1 (addr_i[106]), .Y (n_57));
  AOI22XL g5747__9945(.A0 (n_145), .A1 (wdata_i[20]), .B0 (n_139), .B1
       (wdata_i[84]), .Y (n_56));
  AOI22XL g5688__2883(.A0 (n_147), .A1 (addr_i[34]), .B0 (gnt_o[3]),
       .B1 (addr_i[98]), .Y (n_55));
  AOI22XL g5748__2346(.A0 (n_147), .A1 (wdata_i[51]), .B0 (gnt_o[3]),
       .B1 (wdata_i[115]), .Y (n_54));
  AOI22XL g5749__1666(.A0 (n_145), .A1 (wdata_i[19]), .B0 (n_139), .B1
       (wdata_i[83]), .Y (n_53));
  AOI22X1 g5658__7410(.A0 (n_145), .A1 (addr_i[20]), .B0 (n_147), .B1
       (addr_i[52]), .Y (n_52));
  AOI22X1 g5689__6417(.A0 (n_145), .A1 (wdata_i[4]), .B0 (n_147), .B1
       (wdata_i[36]), .Y (n_51));
  AOI22XL g5750__5477(.A0 (n_145), .A1 (addr_i[10]), .B0 (n_139), .B1
       (addr_i[74]), .Y (n_50));
  AOI22XL g5751__2398(.A0 (n_147), .A1 (addr_i[41]), .B0 (gnt_o[3]),
       .B1 (addr_i[105]), .Y (n_49));
  AOI22X1 g5690__5107(.A0 (n_145), .A1 (addr_i[25]), .B0 (n_147), .B1
       (addr_i[57]), .Y (n_48));
  AOI22XL g5752__6260(.A0 (n_147), .A1 (wdata_i[50]), .B0 (gnt_o[3]),
       .B1 (wdata_i[114]), .Y (n_47));
  AOI22X1 g5659__4319(.A0 (n_145), .A1 (wdata_i[15]), .B0 (n_147), .B1
       (wdata_i[47]), .Y (n_46));
  AOI22X1 g5691__8428(.A0 (n_145), .A1 (wdata_i[3]), .B0 (n_147), .B1
       (wdata_i[35]), .Y (n_45));
  AOI22XL g5692__5526(.A0 (n_145), .A1 (addr_i[2]), .B0 (n_139), .B1
       (addr_i[66]), .Y (n_44));
  AOI22XL g5678__6783(.A0 (n_145), .A1 (addr_i[4]), .B0 (n_139), .B1
       (addr_i[68]), .Y (n_43));
  AOI22XL g5660__3680(.A0 (n_147), .A1 (addr_i[39]), .B0 (gnt_o[3]),
       .B1 (addr_i[103]), .Y (n_42));
  AOI22XL g5693__1617(.A0 (n_147), .A1 (addr_i[33]), .B0 (gnt_o[3]),
       .B1 (addr_i[97]), .Y (n_41));
  AOI22XL g5694__2802(.A0 (n_145), .A1 (addr_i[17]), .B0 (n_139), .B1
       (addr_i[81]), .Y (n_40));
  AOI22XL g5661__1705(.A0 (n_147), .A1 (wdata_i[46]), .B0 (gnt_o[3]),
       .B1 (wdata_i[110]), .Y (n_39));
  AOI22X1 g5765__5122(.A0 (wdata_i[77]), .A1 (n_139), .B0
       (wdata_i[109]), .B1 (gnt_o[3]), .Y (n_38));
  AOI22X1 g5766__8246(.A0 (wdata_i[76]), .A1 (n_139), .B0
       (wdata_i[108]), .B1 (gnt_o[3]), .Y (n_37));
  AOI22X1 g5767__7098(.A0 (addr_i[83]), .A1 (n_139), .B0 (addr_i[115]),
       .B1 (gnt_o[3]), .Y (n_36));
  AOI22X1 g5768__6131(.A0 (wdata_i[75]), .A1 (n_139), .B0
       (wdata_i[107]), .B1 (gnt_o[3]), .Y (n_35));
  AOI22X1 g5770__1881(.A0 (wdata_i[73]), .A1 (n_139), .B0
       (wdata_i[105]), .B1 (gnt_o[3]), .Y (n_34));
  AOI22X1 g5771__5115(.A0 (wdata_i[72]), .A1 (n_139), .B0
       (wdata_i[104]), .B1 (gnt_o[3]), .Y (n_33));
  AOI22X1 g5772__7482(.A0 (addr_i[89]), .A1 (n_139), .B0 (addr_i[121]),
       .B1 (gnt_o[3]), .Y (n_32));
  AOI22X1 g5773__4733(.A0 (wdata_i[70]), .A1 (n_139), .B0
       (wdata_i[102]), .B1 (gnt_o[3]), .Y (n_31));
  AOI22X1 g5774__6161(.A0 (wdata_i[69]), .A1 (n_139), .B0
       (wdata_i[101]), .B1 (gnt_o[3]), .Y (n_30));
  AOI22X1 g5775__9315(.A0 (wdata_i[68]), .A1 (n_139), .B0
       (wdata_i[100]), .B1 (gnt_o[3]), .Y (n_29));
  AOI22X1 g5776__9945(.A0 (wdata_i[67]), .A1 (n_139), .B0
       (wdata_i[99]), .B1 (gnt_o[3]), .Y (n_28));
  AOI22X1 g5777__2883(.A0 (wdata_i[66]), .A1 (n_139), .B0
       (wdata_i[98]), .B1 (gnt_o[3]), .Y (n_27));
  AOI22X1 g5778__2346(.A0 (wdata_i[64]), .A1 (n_139), .B0
       (wdata_i[96]), .B1 (gnt_o[3]), .Y (n_26));
  AOI22X1 g5764__1666(.A0 (addr_i[93]), .A1 (n_139), .B0 (addr_i[125]),
       .B1 (gnt_o[3]), .Y (n_25));
  AOI22X1 g5780__7410(.A0 (addr_i[88]), .A1 (n_139), .B0 (addr_i[120]),
       .B1 (gnt_o[3]), .Y (n_24));
  AOI22X1 g5781__6417(.A0 (addr_i[92]), .A1 (n_139), .B0 (addr_i[124]),
       .B1 (gnt_o[3]), .Y (n_23));
  AOI22X1 g5782__5477(.A0 (addr_i[85]), .A1 (n_139), .B0 (addr_i[117]),
       .B1 (gnt_o[3]), .Y (n_22));
  AOI22X1 g5783__2398(.A0 (addr_i[86]), .A1 (n_139), .B0 (addr_i[118]),
       .B1 (gnt_o[3]), .Y (n_21));
  AOI22X1 g5784__5107(.A0 (addr_i[91]), .A1 (n_139), .B0 (addr_i[123]),
       .B1 (gnt_o[3]), .Y (n_20));
  AOI22X1 g5754__6260(.A0 (wdata_i[74]), .A1 (n_139), .B0
       (wdata_i[106]), .B1 (gnt_o[3]), .Y (n_19));
  AOI22X1 g5758__4319(.A0 (wdata_i[65]), .A1 (n_139), .B0
       (wdata_i[97]), .B1 (gnt_o[3]), .Y (n_18));
  AOI22X1 g5759__8428(.A0 (addr_i[94]), .A1 (n_139), .B0 (addr_i[126]),
       .B1 (gnt_o[3]), .Y (n_17));
  AOI22X1 g5760__5526(.A0 (wdata_i[81]), .A1 (n_139), .B0
       (wdata_i[113]), .B1 (gnt_o[3]), .Y (n_16));
  AOI22X1 g5761__6783(.A0 (addr_i[84]), .A1 (n_139), .B0 (addr_i[116]),
       .B1 (gnt_o[3]), .Y (n_15));
  AOI22X1 g5762__3680(.A0 (wdata_i[79]), .A1 (n_139), .B0
       (wdata_i[111]), .B1 (gnt_o[3]), .Y (n_14));
  AOI22X1 g5763__1617(.A0 (addr_i[90]), .A1 (n_139), .B0 (addr_i[122]),
       .B1 (gnt_o[3]), .Y (n_13));
  AOI22X1 g5779__2802(.A0 (we_i[2]), .A1 (n_139), .B0 (we_i[3]), .B1
       (gnt_o[3]), .Y (n_12));
  AOI22X1 g5785__1705(.A0 (n_106), .A1 (pointer_reg[1]), .B0 (n_151),
       .B1 (pointer_reg[2]), .Y (n_105));
  NAND3BXL g5786__5122(.AN (gnt_o[0]), .B (n_5), .C (n_3), .Y
       (slave_valid_o));
  AOI211X1 g5755__8246(.A0 (n_10), .A1 (pointer_reg[0]), .B0 (n_187),
       .C0 (pointer_reg[1]), .Y (n_11));
  AOI21X1 g5756__7098(.A0 (n_106), .A1 (n_8), .B0 (n_7), .Y (n_9));
  NAND3X1 g5757__6131(.A (n_187), .B (n_8), .C (req_i[2]), .Y (n_6));
  AND2X2 g5787__1881(.A (n_5), .B (gnt_o[1]), .Y (n_147));
  AOI21X1 g5788__5115(.A0 (n_186), .A1 (pointer_reg[0]), .B0
       (pointer_reg[2]), .Y (n_4));
  AND3X2 g5789__7482(.A (n_5), .B (n_3), .C (gnt_o[0]), .Y (n_145));
  INVXL g5790(.A (n_8), .Y (n_2));
  AND2X2 g5793__4733(.A (n_1), .B (gnt_o[2]), .Y (n_139));
  NOR2X1 g5794__6161(.A (pointer_reg[1]), .B (pointer_reg[2]), .Y
       (n_7));
  NAND2BX1 g5791__9315(.AN (pointer_reg[2]), .B (req_i[2]), .Y (n_106));
  NOR2X1 g5795__9945(.A (gnt_o[2]), .B (gnt_o[3]), .Y (n_5));
  NAND2BX1 g5792__2883(.AN (pointer_reg[3]), .B (req_i[3]), .Y (n_8));
  NOR2X1 g5796__2346(.A (req_i[1]), .B (req_i[0]), .Y (n_187));
  INVX1 g5800(.A (req_i[3]), .Y (n_0));
  INVX1 g5797(.A (req_i[1]), .Y (n_10));
  INVX1 g5799(.A (gnt_o[3]), .Y (n_1));
  INVX1 g5801(.A (gnt_o[1]), .Y (n_3));
  INVX1 g5802(.A (pointer_reg[0]), .Y (n_151));
  INVX1 g5798(.A (req_i[2]), .Y (n_186));
endmodule
